### ISSUE TITLE
Order Records by Date Descending (Most Recent First)

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/app#160] opened 2015-12-08 14:31 UTC
As a person using the app I want to see the "*freshest*" records first on the home page so that I see the latest people everyone is looking at.

> Side benefit: people will see fewer profiles without pictures.

**Comment by Adam-JF** [comment] 2015-12-18 11:40
Duplicate of #191

**Closed by Adam-JF** 2015-12-18 11:40 UTC
Labels: duplicate, enhancement, feature idea
