### ISSUE TITLE
Monitor who contact whom

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/app#63] opened 2015-11-11 15:27 UTC
As a user I want to be able to see who has contacted specific user so I won't duplicate the same action

**Pre require** [issue 59](https://github.com/FAC-GM/app/issues/59)

**Comment by iteles** [comment] 2015-12-18 11:13
This will be added to by @Adam-JF as part of his wider vision.

**Comment by iteles** [comment] 2015-12-18 11:23
Duplicate of #72 which has more detail.

**Closed** 2015-12-18 11:24 UTC
Labels: authentication, duplicate
