### ISSUE TITLE
Intoduction text or modal

### ISSUE THREAD

**Issue by jrans** [FAC-GM/app#20] opened 2015-10-22 00:14 UTC
Unclear about how app work or what for looking straight at teh project, just one or two lines introducing the product would be nice.

**Comment by nelsonic** [comment] 2015-10-22 00:28
<img width="764" alt="google-any-instructions" src="https://cloud.githubusercontent.com/assets/194400/10653924/3185ac86-785c-11e5-8bf5-9e996ee56bd7.png">

**Comment by rub1e** [comment] 2015-10-22 10:26
@jrans +1 for the sentiment, if not the gibberish language used to express it

@nelsonic when FAC-GM is in the OED, then and only then can they get away without displaying some sort of explanatory text

**Comment by SimonLab** [comment] 2015-11-11 15:28
@jrans I think the section "What" of the readme describe the purpose of the application. We have also updated th Readme on how to run the application. Do you think the Readme contain enough information to understand the project?

**Comment by Adam-JF** [comment] 2015-11-24 11:51
Duplicate of #92

**Closed** 2015-11-24 11:51 UTC
Labels: question

**Comment by iteles** [comment] 2015-11-24 14:51
Thanks @jrans! Our Product Owner @Adam-JF refined this into a user story relevant to the team as per his note above :blush:
